---
# This playbook contains common plays that will be run on all nodes.

##
 # CSS compiling tools.
 #

#TODO https://stackoverflow.com/questions/26595620/how-to-install-ruby-2-1-4-on-ubuntu-14-04

- name: Include OS specific vars
  tags: ruby
  include_vars: "{{ ansible_os_family }}.yml"

- name: ruby | Add repo for ruby packages
  apt_repository: repo="ppa:brightbox/ruby-ng" state={{ util_repository_state|default('present') }} update_cache=yes
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['19.04'])
  #and (ansible_distribution_version in ['12.04', '13.04', '13.10', '14.04'])
  tags: ruby

- name: ruby | Install rubygems package
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  with_items:
   - rubygems
  #when: (ansible_distribution_version in ['12.04', '13.04', '13.10'])
  tags: ruby
  become: true

- name: ruby | Install ruby package (gem is included now in ruby)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  #when: (ansible_distribution_version not in ['12.04', '13.04', '13.10'])
  with_items:
   - ruby{{ ruby_version }}
   - ruby{{ ruby_version }}-dev
  tags: ruby
  become: true

- name: css | Install SASS
  action: command gem install sass creates=/usr/local/bin/sass
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '13.04', '14.04', '15.04', ])
  #and (ansible_distribution_version in ['12.04', '13.04', '13.10', '14.04'])
  tags: css
  become: true

- name: css | Install Susy (no more --pre required as it's 1.0 now)
  action: command gem install susy
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  #and (ansible_distribution_version in ['12.04', '13.04', '13.10', '14.04'])
  tags: css
  become: true

- name: css | Install Compass
  action: command gem install compass creates=/usr/local/bin/compass
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version in ['12.04', '13.04', '13.10'])
  tags: css
  become: true

- name: css | Install Compass (1)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version in ['14.04', '15.10', '16.10', '18.10']
  with_items:
   - ruby-compass
  become: true

- name: css | Install Compass (2)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version not in ['12.04', '13.04', '13.10', '14.10', '15.10', '16.10', '18.10']
  with_items:
   - compass-blueprint-plugin     # compass-blueprint-plugin is replacing ruby-compass since 19.04
  become: true

- name: css | Install Respond-to
  action: command gem install respond-to
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version not in ['12.04', '13.04', '13.10', '14.04']
  tags: css
  become: true

- name: css | Install cssed
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version in ['16.04'] and css_editor_enabled
  with_items:
   - cssed
  become: true

- name: ruby | Install required packages
  action: "{{ ansible_pkg_mgr }} state={{ util_package_state|default('present') }} name={{ item }}"
  with_items: "{{ ruby_package_list }}"
  tags: ruby
  become: true
