---
# This playbook contains common plays that will be run on all nodes.

##
 # CSS compiling tools.
 #
- name: CSS | Install rubygems package
  action: apt pkg=rubygems state=installed  
  when: "ansible_distribution_version in ['12.04', '13.04', '13.10']"  
  tags: css
  
- name: CSS | Install ruby package (gem is included now in ruby)
  action: apt pkg=ruby{{ ruby_version }} state=installed  
  when: "ansible_distribution_version not in ['12.04', '13.04', '13.10']"  
  tags: css
  
- name: CSS | Install SASS
  action: command gem install sass creates=/usr/local/bin/sass
  tags: css

- name: CSS | Install Susy (no more --pre required as it's 1.0 now)
  action: command gem install susy
  tags: css

- name: CSS | Install Compass
  action: command gem install compass creates=/usr/local/bin/compass
  tags: css

- name: CSS | Install Respond-to
  action: command gem install respond-to
  tags: css

- name: Install cssed
  apt: pkg={{ item }} state=present update_cache=yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and css_editor_enabled
  with_items:
   - cssed
